on: push
jobs: 
    second-job: 
        runs-on: windows-latest
        steps: 
            - run: node --version
            - run: npm --version
            - uses: action/checkout@v3
            - run : npm install
            - run: node index.js

